import{useEffect,useMemo,useState}from"react";
import{screens}from"./manifest";
import type{LoopType,TraceSummary}from"./types";
import{api,type Evidence,type HarnessAgent,type HumanGate,type Project,type RunStatus}from"./api";
import{architectureLayers,codeFiles}from"./codeCatalog";
import"./workspaces.css";

const empty:TraceSummary={requirements:[],tables:[],apis:[],files:[],methods:[]};

export function App(){
 const[view,setView]=useState<"code"|"design">("design"),[selectedFile,setSelectedFile]=useState(0);
 const[approvedFeatures,setApprovedFeatures]=useState<string[]>([]),[codeFeature,setCodeFeature]=useState("");
 const[screenId,setScreen]=useState(screens[0].id),[eventId,setEvent]=useState(screens[0].events[0].id);
 const[loop,setLoop]=useState<LoopType>("DESIGN"),[approved,setApproved]=useState(false);
 const[trace,setTrace]=useState<TraceSummary>(empty),[run,setRun]=useState<RunStatus|null>(null);
 const[projects,setProjects]=useState<Project[]>([]),[evidence,setEvidence]=useState<Evidence[]>([]),[gate,setGate]=useState<HumanGate|null>(null);
 const[harnessType,setHarnessType]=useState<"design"|"code"|null>(null),[agentGroups,setAgentGroups]=useState<Record<"design"|"code",HarnessAgent[]>>({design:[],code:[]}),[agent,setAgent]=useState(0);
 const[drafts,setDrafts]=useState<Record<string,string>>({}),[draftVersions,setDraftVersions]=useState<Record<string,number>>({}),[logs,setLogs]=useState<string[]>([]),[error,setError]=useState("");
 const screen=useMemo(()=>screens.find(x=>x.id===screenId)!,[screenId]);
 const event=useMemo(()=>screen.events.find(x=>x.id===eventId)!,[screen,eventId]);
 const featureKey=`${screenId}/${eventId}`;
 const agents=agentGroups[harnessType||"design"];
 const completedFeatures=useMemo(()=>approvedFeatures.flatMap(key=>{const[approvedScreenId,approvedEventId]=key.split("/"),approvedScreen=screens.find(item=>item.id===approvedScreenId),approvedEvent=approvedScreen?.events.find(item=>item.id===approvedEventId);return approvedScreen&&approvedEvent?[{key,screen:approvedScreen,event:approvedEvent}]:[]}),[approvedFeatures]);
 const report=(message:string)=>setLogs(v=>[...v.slice(-11),message]);
 const fail=(e:unknown)=>setError(e instanceof Error?e.message:"요청 처리에 실패했습니다.");
 useEffect(()=>{Promise.all([api.trace(screenId,eventId),api.snapshots(screenId,eventId),api.implementationQueue(screenId)]).then(([nextTrace,snapshots,queue])=>{setTrace(nextTrace);setApproved(snapshots.some(item=>item.status==="A_APPROVED"));const ready=queue.filter(item=>item.status==="IMPLEMENTATION_READY"&&item.screenId&&item.eventId).map(item=>`${item.screenId}/${item.eventId}`);setApprovedFeatures(items=>[...new Set([...items,...ready])])}).catch(fail)},[screenId,eventId]);
 useEffect(()=>{api.projects().then(setProjects).catch(fail)},[]);
 useEffect(()=>{if(!run?.runId)return;const timer=setInterval(()=>api.runStatus(run.runId).then(setRun).catch(()=>{}),2000);return()=>clearInterval(timer)},[run?.runId]);
 useEffect(()=>{if(!run?.runId)return;api.evidence(run.runId).then(setEvidence).catch(fail);if(run.state==="HUMAN_TEST")api.gates(run.runId).then(x=>setGate(x[0]||null)).catch(fail)},[run?.runId,run?.phase,run?.state]);
 const selectScreen=(id:string)=>{const next=screens.find(x=>x.id===id)!;const nextEvent=next.events[0].id;setScreen(id);setEvent(nextEvent);setApproved(approvedFeatures.includes(`${id}/${nextEvent}`));setLoop("DESIGN")};
 const selectEvent=(id:string)=>{setEvent(id);setApproved(approvedFeatures.includes(`${screenId}/${id}`))};
 const approve=async()=>{setError("");try{const result=await api.approve(screenId,eventId);setApproved(true);setApprovedFeatures(items=>items.includes(featureKey)?items:[...items,featureKey]);setCodeFeature(featureKey);report(`설계 v${result.designVersion} 확정 · 구현대기열 생성`)}catch(e){fail(e)}};
 const reopen=async()=>{setError("");try{await api.reopen(screenId,eventId);setApproved(false);setApprovedFeatures(items=>items.filter(item=>item!==featureKey));setLoop("DESIGN");report("설계 재개방 · 이전 구현 결과 STALE")}catch(e){fail(e)}};
 const start=async()=>{setError("");try{const created=await api.run(loop,screenId,eventId);const result=await api.runStatus(created.runId).catch(()=>created);setRun(result);report(`${result.phase} 실행 시작`)}catch(e){fail(e)}};
 const advance=async()=>{if(!run)return;setError("");try{const result=await api.advanceRun(run.runId,true,"UI에서 단계 증거 확인");setRun(result);report(`${result.phase||result.state} 검증 완료`)}catch(e){fail(e)}};
 const cancel=async()=>{if(!run)return;try{const result=await api.cancelRun(run.runId);setRun({...run,...result});report("실행 취소 완료")}catch(e){fail(e)}};
 const retry=async()=>{if(!run)return;try{const result=await api.retryRun(run.runId);setRun(result);setEvidence([]);report("새 실행으로 재시도 시작")}catch(e){fail(e)}};
 const decide=async(decision:"APPROVE"|"REJECT")=>{if(!gate||!run)return;try{const result=await api.decideGate(gate.id,decision);setRun({...run,state:result.state});setGate({...gate,decision});report(`HUMAN_TEST ${decision}`)}catch(e){fail(e)}};
 const openHarness=async(type:"design"|"code")=>{setError("");try{const[design,designSaved,code,codeSaved]=await Promise.all([api.harness("design"),api.harnessDrafts("design"),api.harness("code"),api.harnessDrafts("code")]);const saved=[...designSaved,...codeSaved],all=[...design,...code],byId=Object.fromEntries(saved.map(x=>[x.agentId,x]));setAgentGroups({design,code});setDrafts(Object.fromEntries(all.map(x=>[x.id,byId[x.id]?.content||x.content])));setDraftVersions(Object.fromEntries(all.map(x=>[x.id,byId[x.id]?.version||0])));setAgent(0);setHarnessType(type)}catch(e){fail(e)}};
 const selectHarnessAgent=(type:"design"|"code",index:number)=>{setHarnessType(type);setAgent(index)};
 const saveDraft=async()=>{if(!harnessType||!agents[agent])return;const id=agents[agent].id;try{const saved=await api.saveHarnessDraft(harnessType,id,drafts[id]||"",draftVersions[id]||0);setDraftVersions(v=>({...v,[id]:saved.version}));report(`${id} draft v${saved.version} 저장`)}catch(e){fail(e)}};
 const publish=async()=>{if(!harnessType)return;try{for(const item of agents){const checked=await api.validateHarness(harnessType,item.id,drafts[item.id]||"");if(!checked.valid)throw new Error(`${item.name}: ${checked.errors.join(", ")}`)}const files=Object.fromEntries(agents.map(item=>[item.id,drafts[item.id]||""]));const result=await api.publishHarness(harnessType,files);report(`하네스 v${result.version} 원자적 게시`);setHarnessType(null)}catch(e){fail(e)}};
 const selectLayer=(layer:string)=>{const index=codeFiles.findIndex(file=>file.layer===layer);setView("code");if(index>=0)setSelectedFile(index);report(`${layer} 코드 열기`)};
 const mockup=<div className="browser"><div className="dots">● ● ● <span>목업 미리보기</span></div><div className="mock"><h2>{event.name}</h2><div className="filters"><label>검색어<input aria-label="검색어"/></label><label>상태<select aria-label="상태"><option>전체</option><option>진행중</option></select></label><button onClick={()=>report("검색 조건 초기화")}>초기화</button><button className="primary" onClick={()=>report(`${eventId} 조회 실행`)}>조회</button></div><table><thead><tr><th>이벤트</th><th>루프 상태</th><th>현재 단계</th></tr></thead><tbody><tr><td>{eventId}</td><td>{run?.state||"대기"}</td><td>{run?.phase||"-"}</td></tr></tbody></table></div></div>;
 return <div className="app">
  <header><strong>Forge<b>Flow</b></strong><label>프로젝트 <select aria-label="프로젝트"><option>ForgeFlow Workspace</option>{projects.map(x=><option key={x.id}>{x.name}</option>)}</select></label><nav><button className={view==="code"?"active":""} onClick={()=>setView("code")}>코드 작성</button><button className={view==="design"?"active":""} onClick={()=>setView("design")}>설계 화면</button></nav><button onClick={()=>openHarness(loop==="DESIGN"?"design":"code")}>하네스</button><button onClick={()=>report(`서버 저장됨 · 증거 ${evidence.length}건`)}>저장 상태</button></header>
  <div className="shell">
   <aside className="left"><h3>화면·이벤트 디렉터리</h3>{screens.map(s=><section key={s.id}><button className={s.id===screenId?"selected":""} onClick={()=>selectScreen(s.id)}>{s.id}<small>{s.name}</small></button>{s.id===screenId&&s.events.map(e=><button className={e.id===eventId?"selected event":"event"} onClick={()=>selectEvent(e.id)} key={e.id}>{e.id} · {e.name}</button>)}</section>)}</aside>
   <main>
    <div className="context"><span>화면 잠금</span><b>{screenId}</b><span>이벤트 추적 잠금</span><b>{eventId}</b></div>
    <div className="layers"><span>{view==="design"?"SSOT 설계":"아키텍처"}</span>{view==="design"?<><b>요구사항</b><b>테이블 설계</b><b>API 계약</b><b>목업</b></>:architectureLayers.map(x=><button className={codeFiles[selectedFile]?.layer===x?"selected":""} key={x} onClick={()=>selectLayer(x)}>{x}</button>)}</div>
    {view==="code"&&<div className="workspace codeWorkspace"><div className="hero"><div><small>IMPLEMENTATION WORKSPACE</small><h1>코드 작성</h1><p>설계가 확정된 기능을 선택해 구현 코드를 작성합니다.</p></div>{codeFeature&&<em>{codeFeature}</em>}</div><div className="implementationLayout"><aside className="featureQueue"><h3>설계 완료 기능</h3>{completedFeatures.length?completedFeatures.map(item=><button className={codeFeature===item.key?"selected":""} key={item.key} onClick={()=>setCodeFeature(item.key)}><b>{item.event.id} · {item.event.name}</b><small>{item.screen.name}</small><span>DESIGN APPROVED</span></button>):<p>설계 화면에서 기능을 설계 확정하면 이 목록에 추가됩니다.</p>}</aside><div className={`codePanel ${codeFeature?"":"codeDisabled"}`}><aside className="fileTree"><h3>관련 구현 파일</h3>{codeFiles.map((file,index)=><button disabled={!codeFeature} key={file.path} className={index===selectedFile?"selected":""} onClick={()=>setSelectedFile(index)}><b>{file.name}</b><small>{file.layer}</small></button>)}</aside><section className="codeEditor">{codeFeature?<><div className="editorHead"><span>{codeFiles[selectedFile].path}</span><span>{codeFiles[selectedFile].language}</span></div><pre><code>{codeFiles[selectedFile].content}</code></pre></>:<div className="emptyEditor">설계 완료 기능을 먼저 선택하세요.</div>}</section></div></div></div>}
    {view==="design"&&<div className="workspace designWorkspace"><div className="hero"><div><small>{event.id} · {event.kind}</small><h1>설계 화면 · {screen.name}</h1><p>{event.name}</p></div><em>{approved?"A 설계 확정":"A 설계 필요"}</em></div><div className="designGrid"><article className="mockupCard"><h2>목업</h2>{mockup}</article><article className="ssotCard"><h2>SSOT 설계 정보</h2>{[{label:"요구사항",values:trace.requirements},{label:"테이블 설계",values:trace.tables},{label:"API 계약",values:trace.apis},{label:"관련 파일",values:trace.files},{label:"관련 메서드",values:trace.methods}].map(group=><section key={group.label}><b>{group.label}</b>{group.values.length?group.values.map(value=><span key={value}>{value}</span>):<span>정의 없음</span>}</section>)}</article><article className="artifactCard"><h2>SSOT 산출물</h2>{["manifest.json","requirements.ref.json","api-contract.ref.json","data-model.ref.json","mockup.ref.json","review.ref.json"].map(x=><div className="artifact" key={x}>{x}<span>{approved?"READY":"DRAFT"}</span></div>)}</article></div></div>}
    <div className="threads"><div className="tabs"><button className={loop==="DESIGN"?"active":""} onClick={()=>{setLoop("DESIGN");setView("design")}}>설계루프</button><button disabled={!approved} className={loop==="IMPLEMENT"?"active":""} onClick={()=>{setLoop("IMPLEMENT");setView("code");setCodeFeature(featureKey)}}>구현루프</button><button aria-label="전체 하네스 열기" onClick={()=>openHarness(loop==="DESIGN"?"design":"code")}>📄</button></div><div className="console"><div><b>{loop==="DESIGN"?"A 설계루프":"B 구현루프"}</b><p>{screenId} · {eventId} · 증거 {evidence.length}</p><button onClick={start}>실행</button>{run&&<button onClick={advance} disabled={["CANCELLED","ACCEPTED","HUMAN_TEST"].includes(run.state)||run.phaseStatus==="PASS"}>단계 검증</button>}{run&&!["CANCELLED","ACCEPTED","A_REVIEW"].includes(run.state)&&<button onClick={cancel}>취소</button>}{run&&["CANCELLED","B_REPAIR"].includes(run.state)&&<button onClick={retry}>재시도</button>}{run?.state==="HUMAN_TEST"&&<><button className="primary" onClick={()=>decide("APPROVE")}>사람 승인</button><button onClick={()=>decide("REJECT")}>반려</button></>}{loop==="DESIGN"&&(approved?<button onClick={reopen}>설계 다시 열기</button>:<button onClick={approve}>설계 확정</button>)}</div><div className="runOutput"><div className="agentAssignment"><b>현재 단계 담당 Agent</b>{run?.activeAgents?.length?run.activeAgents.map(item=><span key={item.id}>{item.name}</span>):<span>루프 실행 전</span>}</div><pre>{error&&`BLOCKED: ${error}\n`}{logs.join("\n")||"실행 대기"}</pre></div></div></div>
   </main>
   <aside className="right"><h3>서버 이벤트 매핑</h3>{Object.entries(trace).map(([key,values])=><section key={key}><b>{key}</b>{values.length?values.map(x=><div key={x}>{x}</div>):<div>연결 없음</div>}</section>)}</aside>
  </div>
  {harnessType&&<div className="overlay"><div className="modal"><div className="modalHead"><h2>전체 하네스 · 설계 {agentGroups.design.length} · 코드 {agentGroups.code.length}</h2><button onClick={()=>setHarnessType(null)}>닫기</button></div><div className="harness"><aside><h3>설계루프 Agent</h3>{agentGroups.design.map((x,i)=><button className={harnessType==="design"&&i===agent?"selected":""} onClick={()=>selectHarnessAgent("design",i)} key={x.id}>{i+1}. {x.name}</button>)}<h3>구현루프 Agent</h3>{agentGroups.code.map((x,i)=><button className={harnessType==="code"&&i===agent?"selected":""} onClick={()=>selectHarnessAgent("code",i)} key={x.id}>{i+1}. {x.name}</button>)}</aside><section>{agents[agent]&&<><div className="harnessContext"><b>{harnessType==="design"?"설계루프":"구현루프"}</b><code>{agents[agent].file} · draft v{draftVersions[agents[agent].id]||0}</code></div><textarea value={drafts[agents[agent].id]||""} onChange={e=>setDrafts(v=>({...v,[agents[agent].id]:e.target.value}))}/></>}</section></div><footer><span>{harnessType==="design"?"설계":"코드"} 하네스 편집 중</span><button onClick={saveDraft}>Draft 저장</button><button className="primary" onClick={publish}>현재 루프 검증 후 게시</button></footer></div></div>}
 </div>
}
